export const NEW_PROJECT_FORM = "NEW_PROJECT_FORM"
export const PROJECT_LIST = "PROJECT_LIST"
export const ADD_PROJECT = "ADD_PROJECT"
export const PROJECT_FORM_ERROR = "PROJECT_FORM_ERROR"
export const CURRENT_PROJECT = "CURRENT_PROJECT"
export const DELETE_PROJECT = "DELETE_PROJECT"

export const PROJECT_TASKS = "PROJECT_TASKS"
export const ADD_TASK = "ADD_TASK"
export const TASK_FORM_ERROR = "TASK_FORM_ERROR"
export const DELETE_TASK = "DELETE_TASK"




