export const NEW_PROJECT_FORM = "NEW_PROJECT_FORM"
export const PROJECT_LIST = "PROJECT_LIST"
export const ADD_PROJECT = "ADD_PROJECT"
export const SHOW_ERROR = "SHOW_ERROR"
export const CURRENT_PROJECT = "CURRENT_PROJECT"
export const DELETE_PROJECT = "DELETE_PROJECT"




