export const NEW_PROJECT_FORM = "NEW_PROJECT_FORM"
export const PROJECT_LIST = "PROJECT_LIST"
export const ADD_PROJECT = "ADD_PROJECT"
export const PROJECT_FORM_ERROR = "PROJECT_FORM_ERROR"
export const CURRENT_PROJECT = "CURRENT_PROJECT"
export const DELETE_PROJECT = "DELETE_PROJECT"

export const PROJECT_TASKS = "PROJECT_TASKS"
export const ADD_TASK = "ADD_TASK"
export const TASK_FORM_ERROR = "TASK_FORM_ERROR"
export const DELETE_TASK = "DELETE_TASK"
export const CURRENT_TASK = "CURRENT_TASK"
export const EDIT_TASK = "EDIT_TASK"

export const SHOW_ALERT = "SHOW_ALERT"
export const HIDE_ALERT = "HIDE_ALERT"

export const REGISTRATION_SUCCESSFUL = "REGISTRATION_SUCCESSFUL"
export const REGISTRATION_ERROR = "REGISTRATION_ERROR"
export const GET_USER = "GET_USER"
export const LOGIN_SUCCESSFUL = "LOGIN_SUCCESSFUL"
export const LOGIN_ERROR = "LOGIN_ERROR"
export const LOGOUT = "LOGOUT"






